Profil oldal
CorvinusGeekClub/GeekPlatform pull request #14
Opened 2017-04-06 16:16 UTC by FruzsiCsonka

Profil oldal: van ViewModel, Controller és minden ami kell, kivétel a buborékok

2017-04-06 19:58 UTC, marcelltoth requested changes
Tök jó lesz, de a kurzusok meg a skillek megjelenítését meg kell még csinálni, majd megoldom szerintem.

2017-04-07 21:15 UTC, z2s8 requested changes
Szép munka :+1:

2017-04-07 21:15 UTC, z2s8 commented on src/GeekPlatform/Views/Profil/Index.cshtml
> +                        <p>@Model.TagsagKezdete:</p>
Ezeknél a felsorolálsos adatoknál (`Tagság kezdete`, `Tagság várható vége`, `Munkahely, pozíció`) marajdon meg a kíírt tulajdonság is, és mellé tegyük be az értéket, ahogy a [képen](https://drive.google.com/file/d/0Bz62sjhk4NCfRU1BR3R0ZXJuVTQ/view)

Tehát az itt lejjebbi `<p>Teszt szöveg, ami elég hosszú</p>` részek helyére jöhetnének a modelles adatok

2017-04-07 21:23 UTC, z2s8 commented on src/GeekPlatform/ViewModels/Profil/ProfilViewModel.cs
> +            PozicioTeamTagsag = user.TeamMember;
A dátumos mezőket lehetne `String`-ként betenni ide, és akkor tudjuk magyarosra formázni [ahogy Bálint csinálta egy másik helyen](https://github.com/CorvinusGeekClub/GeekPlatform/pull/15/files#diff-31e3e939bffd5983411ca620a8d5ca11)

2017-04-08 14:18 UTC, enarax commented on src/GeekPlatform/ViewModels/Profil/ProfilViewModel.cs
> +            PozicioTeamTagsag = user.TeamMember;
Így is tudjuk magyarosan formázni amúgy, view-ben nyugodtan lehet paraméteresen tostringelni. (Persze nem mondom hogy az jobb megoldás, egyelőre az egyszerűség miatt én is efelé hajlok csak meg akartam jegyezni hogy ebben is van ráció.)

2017-04-08 17:17 UTC, marcelltoth approved these changes

2017-04-08 18:55 UTC, z2s8 approved these changes
Angol OS-en a dátumok jók már, remélem jó helyen setteltem az alapértelmezettet

2017-04-09 10:37 UTC, merged