Page kurzusaim
CorvinusGeekClub/GeekPlatform pull request #15
Opened 2017-04-06 16:19 UTC by nblnt

Kurzusaim oldal létrehozása.

2017-04-06 20:00 UTC, enarax commented on src/GeekPlatform/Controllers/KurzusaimController.cs
> +            IEnumerable<Course> aktivKurzusok = kurzusok.Where(c => c.IsRunning).ToList();
Biztos hogy az isRunning jó feltétel?
Gondolj azokra amik fel vannak véve de még nem indultak el.

2017-04-06 20:04 UTC, marcelltoth requested changes

2017-04-06 20:04 UTC, enarax commented on src/GeekPlatform/ViewModels/Kurzusaim/KurzusTematikaViewModel.cs
> +            Datum = datum.Year.ToString() + "." + datum.Month.ToString("00") + "." + datum.Day.ToString("00") + ". " + datum.Hour.ToString("00") + ":" + datum.Minute.ToString("00");
https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx
pls :D

2017-04-06 20:04 UTC, enarax commented on src/GeekPlatform/Controllers/KurzusaimController.cs
> +            IEnumerable<Course> aktivKurzusok = kurzusok.Where(c => c.IsRunning).ToList();
Biztos hogy az isRunning jó feltétel?
Gondolj azokra amik fel vannak véve de még nem indultak el.

2017-04-07 20:01 UTC, nblnt commented on src/GeekPlatform/ViewModels/Kurzusaim/KurzusTematikaViewModel.cs
> +            Datum = datum.Year.ToString() + "." + datum.Month.ToString("00") + "." + datum.Day.ToString("00") + ". " + datum.Hour.ToString("00") + ":" + datum.Minute.ToString("00");
jogos, javítom 😄

2017-04-07 20:09 UTC, nblnt commented on src/GeekPlatform/Controllers/KurzusaimController.cs
> +            IEnumerable<Course> aktivKurzusok = kurzusok.Where(c => c.IsRunning).ToList();
Ezek szerint az isRunning a kurzus legelső alkalmáig false-t fog visszaadni?

2017-04-07 20:15 UTC, z2s8 commented on src/GeekPlatform/Controllers/KurzusaimController.cs
> +            IEnumerable<Course> aktivKurzusok = kurzusok.Where(c => c.IsRunning).ToList();
Szerintem amire már lehet jelentkezni az legyen `IsRunning`

2017-04-07 20:41 UTC, z2s8 submitted a review, later dismissed
Többi :ok_hand: !

2017-04-07 20:41 UTC, z2s8 commented on src/GeekPlatform/Views/Kurzusaim/Index.cshtml
> +                                <div class="panel-course-col-text">@aktivKurzus.AktualisTematika.Temakor</div>
Nekem itt egy UI-s megjegyzésem lenne: írjuk ki ennél is az alkalom dátumát, mint a következő óránál van - véletlenül maradhatott le a grafika tervről

2017-04-08 14:32 UTC, marcelltoth approved these changes

2017-04-08 14:54 UTC, merged