Create initial database tables
CorvinusGeekClub/GeekPlatform pull request #3
Opened 2017-03-19 22:15 UTC by z2s8

- Add new SQL project `GeekDatabase` inside solution
- Add tables

2017-03-21 11:23 UTC, marcelltoth requested changes
Competency és Member_Competency:
Ezt az egész comptetency dolgot nem értem, ez kint van / lesz a siteon jelenleg bárhol? (Lehetőség szerint ne dolgozzunk előre, már csak azért sem mert minden ilyen upgrade jó kis tanulós projekt egy csapatnak) 

Course:
A Course.Icon_S/M/L az szerintem full redundáns, egy filenevet kellene tárolni és azt kódból átméretezni és valamiylen logika szerint eltárolni a nevét: pl <name>.m/s.jpg Úgy sem fog senki 3 különböző képet gyártani hozzá.
Hiányzik az Is_Active illetve az Is_Running (active=false látszólag "töröl" a rendszerből, a running azt határozza meg hogy tart-e még)
Illetve kéne egy jelentkezési határidő is, mert 1. az Is_Running-ból nem derül ki hogy előtte vagy utána vagyunk 2. nem biztos hogy előző napig el akarjuk fogadni a jelentkezéseket feltétlenül.

Course_Enrollment:
Enrollmentnél azt beszéltük utolsó meetingen azt beszéltük hogy nincs approval, automatikusan elfogadunk mindenkit aztán legfeljebb törölni lehet ha valakit mégsem akarunk. Úgyszintén az Is_Finished-et nem értem, az nem a course-nak a tulajdonsága? (Én logikám szerint azt akarja jelenteni hogy megcsinálta-e a kurzust, vagy nem?) Ezen kívül a kulcsnak egy (Profile_Id,Course_Id) composite-nak kellene lennie, a mostani setup megengedi ugyanannak az embernek a kétszeri jeelntkezését, gondolom ezt nem szeretnénk.

Course_News:
Teljesen indokolatlan a title-ben a non-variable CHAR, úgyszintén a 40 karakteres limit (bár utóbbiról meg tudtok győzni). Csak azért nem szeretem ezeket a limiteket mert ha rájövünk később hogy több kell (elég kevés az a 40) akkor nem elég a kódot módosítani, schemát is kell. Egyszerűbb ha itt MAX (vagy legalább vmi 128).

Course_Thematics:
A Homework_Description lehetne NULL, azokat a heteket jelölné amikor nincs házi (ami nem ugyan az mint a "" ami csak azt jelenti hogy még nincs kitöltve)
Ami viszont tuti hogy itt megint gázos a PK, (Course_Id, Week_Number) kompozit kéne.

Homework_Upload:
Tölthet fel többet is egy házihoz? Ezt nem beszéltük meg de én arra szavaznék (egyszerűség kedvéért prog illetve háziellenőrzés szempontjából) hogy ne, akkor ezt is át kéne kulcsozni. 

Profile:
Megint teljesen indokolatlanul limitelünk. A Major gondolom a szak, az teljesen nyugodtan tud 30+ lenni, a Phone biztos hogy nem fér bele 12-be: `echo "+36/20 57-37-871" | wc`. A 200-as nem foglal semmivel több helyet mint a 12-es.

2017-03-21 13:05 UTC, z2s8 commented
**Competency és Member_Competency:** ez a Skill részleg a profil oldalon (jobb alsó lapka)

**Course**: `Is_Active`, `Is_Running` tenlyeg kell, hatarido lehet mondjuk `Sign_up_Deadline` `Is_Active`-t mas tablakba is lehet be kene rakni amugy ilyen logikaval: `Homework_Upload`?

**Course_Enrollment**:  `Is_Finished` azt jelenti hogy elvegezte-e, approve-ra az milyen megoldás ha default ertek `true`, es approver `null`?
Kulcs valtoztatas jogos

**Course_News**: title nchar mögött nem tudom milyen megfontolás áll @Polgarmester ?

**Homework_Upload**: tölthessen fel többet szerintem, különben nem tudja szerkeszteni a már beadott megoldást, UX szempontból tudjuk mondani hogy csak a legfrisseb filet javítják ki

**Profile**: telefonszam: lehet tobb, mint 12 a limit, de szemetet ne fogadjunk bele, aka az egyeduli valid formatum: `+36302119899` es `06302119899`, utana UI-n meg lehet kulon is jeleniteni

2017-03-21 13:11 UTC, enarax commented
**Competency és Member_Competency:** fine

**Course**: Igen, Is_Active máshova is jó

**Course_Enrollment:** Jaj értem, félreértettem a finishedet. Szerintem akkor is lényegtelen az approver, nincs benne a specbe. Majd belerakjuk ha olyan lesz, egyelőre csak bonyolít.

**Homework_Upload:** jogos

**Profile**: akkor legyen a +36-os, az az elterjedtebb és nemzetközi, de akkor aszerint.

2017-03-24 12:33 UTC, marcelltoth approved these changes

2017-03-24 12:45 UTC, z2s8 commented on GeekDatabase/Course_Enrollment.sql
> -    [Is_Enrollment_Approved] BIT NOT NULL,
ha nincs `Is_Enrollment_Approved]` bit, akkor hogy tiltasz el kurzusjelentkezest? szerintem ez maradjon

2017-03-24 12:48 UTC, enarax commented on GeekDatabase/Course_Enrollment.sql
> -    [Is_Enrollment_Approved] BIT NOT NULL,
Hát ezzel nem jelentkezést tudnál letiltani, hanem egy konkrét jelentkezést disapprovolni. Szerintem nincs rá nagy szükség, megbeszéléses alapon lesz hogy ki jön mire, nem azon múlik hogy itt be tudja jelölni vagy nem. Törölni meg majd fogunk tudni ha véletlenül jeletkezne vki

2017-03-24 12:57 UTC, z2s8 commented
Merged at 0ee472c

2017-03-24 12:57 UTC, merged