Jelentkezés oldal
CorvinusGeekClub/GeekPlatform pull request #9
Opened 2017-03-29 15:29 UTC by FruzsiCsonka

Controller, View, View Model kész (Marci segített egy kicsit)

2017-03-30 02:38 UTC, z2s8 requested changes
Szép munka, pár változást még javasoltam 👍

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/Models/ViewModels/CourseViewModel.cs
> +            ImgUrl = c.IconFileName;
Itt használhatnánk már teljes valós URL-t. Mondjuk `~/uploads/{c.IconFileName}` ?

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/ViewModels/Jelentkezes/CourseViewModel.cs
> +    }
Kelleni fog az `IsWorkshop` tulajdonság is (ld: View)

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/ViewModels/Jelentkezes/JelekezesViewModel.cs
> +    public class JelekezesViewModel : ViewModelBase
*Jelekezes*? Legyen inkább Jele**nt**kezes

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/Views/Jelentkezes/Index.cshtml
> +        <div class="row workshopcim"><h4>@i.CourseName</h4></div>
itt attól függően kellene **workshop** vagy **aktiv** előtagos class, hogy workshop-e (`IsWorkshop`)

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/Views/Jelentkezes/Index.cshtml
> +        <div class="row workshopoktato"><span>@i.Instructor</span></div>
mint felette

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/Controllers/JelentkezesController.cs
> +                var vm = new JelekezesViewModel(context.Course.ToList());
Csak azokat a kurzusokat jelenítsük meg, ami `IsActive` és `SignUpDeadline` még nem járt le
\+ _ha_ `JelekezesViewModel.cs` kommenten **2)** megoldást választjuk akkor még az a szűrés

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/ViewModels/Jelentkezes/JelekezesViewModel.cs
> +            Courses = courselist.Select(x => new CourseViewModel(x)).ToList();
Szerintem itt tegyük hozzá `CourseEnrollment`-ből, hogy már jelentkezett-e a kurzusra, és írjuk ki View-ba is, **vagy** csak Controllerben szűrjük ki a már bejelentkezett kurzusokat, és hide

2017-03-30 02:38 UTC, z2s8 commented on src/GeekPlatform/Views/Jelentkezes/Index.cshtml
> +            <div class="col-md-2 kozep"><button class="btn-lg jelentkezz">Jelentkezés</button></div>
Ezt a gombot deaktiválhatnánk _ha_ `JelekezesViewModel.cs`-s kommentből **1)** megoldást választjuk

2017-04-02 15:24 UTC, enarax commented on src/GeekPlatform/ViewModels/Jelentkezes/JelekezesViewModel.cs
> +            Courses = courselist.Select(x => new CourseViewModel(x)).ToList();
Utóbbi egyszerűbb, szóval most mindenképp az lesz, plusz alapból is logikus az is mert közvetlen felette van egy "kurzusaim" menüpont ahol pont a fordított szűrő lesz.

2017-04-05 19:16 UTC, Polgarmester commented
Csáó! Megcsináltunk mindent faszán. kecske

2017-04-06 00:02 UTC, z2s8 requested changes
Alright, jó _lesz_ ez már csak kisebb dolgok vannak hátra :), a line kommenteken kívül:

* f58d5fa kommitot vissza kéne vonni, ront az átláthatóságon (`git revert f58d5fa`)
* képek URL-jei még mindig nem teljesek (lásd előző review)

2017-04-06 00:02 UTC, z2s8 commented on src/GeekPlatform/Views/Jelentkezes/Index.cshtml
> +                    <button class="btn-lg jelentkezz" disabled>Csicskagyerek</button>
disabled gombot inkább `btn disabled` [classokkal csináljunk](https://www.w3schools.com/Bootstrap/tryit.asp?filename=trybs_ref_btn_disabled&stacked=h), egyértelműbb az UX;
Feliratra ajánlanám a `Már jelentkeztél` szöveget eh

2017-04-06 00:02 UTC, z2s8 commented on src/GeekPlatform/Views/Jelentkezes/Index.cshtml
> +    <div class="alert alert-success" role="alert">Ügyes voltál hülyegyerek</div>
Hmm, `Sikeres kurzusjelentkezés`? Nem kötekedésből, csak tudom hogy benne fog maradni demo-ra

2017-04-06 12:06 UTC, enarax commented
Seed data marad mert a régi rossz, gyors megoldásnak teljesen jó lesz így

2017-04-06 15:23 UTC, merged